name: ci
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install nextest
      shell: bash
      run: |
        curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Run test
      uses: actions-rs/cargo@v1
      with:
        command: nextest
        args: run

    - name: Run test without action
      run: cargo nextest run --profile ci --retries 1
